### ISSUE TITLE
Add size parameters to control thumbnail size

### ISSUE THREAD

**Issue by Snailedlt** [Snailedlt/Markdown-Videos#10]
- width (default=320)
- height (default=180)

**Comment by David-davidlxl** [comment]
Has there been a solution to this yet? How can I control the size of the thumbnail?

**Comment by David-davidlxl** [comment]
Thanks for the update. Are you currently working on it by any chance? I ask because when I embed YouTube videos using your project, the link (e.g., https://markdown-videos.deta.dev/youtube/MtSMa02I1Co) takes me to a page that says "Service No Longer Available" (and it used to be working). It'd be great if this could be fixed soon

**Comment by Snailedlt** [comment]
@David-davidlxl I'm not atm... I'm busy with house renovations and work atm, but when that's done I will look at fixing markdown-videos again.

The reason it's not working atm is that deta just deprecated Deta Cloud, so I have to migrate to Deta Space... more info here: https://github.com/Snailedlt/Markdown-Videos/issues/27

**Comment by David-davidlxl** [comment]
Could you add instructions in README on how to pass the width and height parameters in GitHub Markdown? With an example? Thank you

**Comment by Snailedlt** [comment]
@David-davidlxl Yeah good idea. I'll do that next time I work on this :)
Until then you can see examples here: https://markdown-videos.vercel.app/docs

**Comment by Snailedlt** [comment]
@David-davidlxl Does this look like an okey solution? #38

**Comment by David-davidlxl** [comment]
@Snailedlt Thank you! This is much better, but I have a couple of suggestions:
1) use "width=320" and "height=180" in the examples just to be consistent with the default values
2) add another example (maybe outside the table) showing how to set both parameters simultaneously (it took me a while to find your example in https://github.com/Snailedlt/Markdown-Videos/issues/37 to figure out how to do it); setting only one parameter to a nondefault value would leave the image distorted, so it would be most useful if the user knows how to set both

**Comment by Snailedlt** [comment]
@David-davidlxl Thanks for the suggestions. Setting multiple parameters is the same for pretty much every REST API, which is why I didn't include an example for it. If you need examples you can always look at the docs.

That said, I agree that the default width and height should be more clear, so I'll add a "default" column to the parameters table (see #38 ) :)
