### ISSUE TITLE
Add support for youtube shorts

### ISSUE THREAD

**Issue by Snailedlt** [Snailedlt/Markdown-Videos#206]
related to #202

**Comment by Snailedlt** [comment]
Probably the only thing needed is to update the regex: https://github.com/Snailedlt/Markdown-Videos/blob/65cc03ff7d631f84386cd080bc0018681e88ece4/apps/api/src/util.py#L18C4-L18C4

**Comment by Zingzy** [comment]
Hey, I would like to work on this issue, so could you please assign me this issue for Hacktoberfest 2024?
