### ISSUE TITLE
Fix blurry-image issue after scaling up

### ISSUE THREAD

**Issue by David-davidlxl** [Snailedlt/Markdown-Videos#39]
After setting the `width` and `height` parameters to higher-than-default values, the image appears somewhat blurry. For example, even though my YouTube video has a maximum resolution of 1080p, when I set `width` and `height` to `960` and `540`, respectively (https://markdown-videos.vercel.app/youtube/MtSMa02I1Co?width=960&height=540), the image is blurry:
![](https://markdown-videos.vercel.app/youtube/MtSMa02I1Co?width=960&height=540)

I don't know if it's intentional or not. But there should be a way to make the image nonblurry. For example, https://img.youtube.com/vi/MtSMa02I1Co/maxresdefault.jpg would generate the maximum-resolution, nonblurry image.

As a side note (in addition to this blurry issue), perhaps you can consider grabbing the maximum-resolution width and height values from, for example, https://img.youtube.com/vi/{video_id}/maxresdefault.jpg, and use those values as the default values? And/or use the image from https://img.youtube.com/vi/{video_id}/maxresdefault.jpg and add the play button on top?

**Comment by Snailedlt** [comment]
Thanks for shedding light on this!
If you feel up to it you're more than welcome to make a PR on this

**Comment by David-davidlxl** [comment]
No problem! Unfortunately even though I have some amount of Python experience, I have very little knowledge of API--I'll have to leave it up to you to implement this when you get a chance:)

**Comment by Snailedlt** [comment]
@David-davidlxl if you want, I can help you along :)
The build instructions are in the README... and if you need any more help I can assist you through discord. My username is `snailedlt`

**Comment by David-davidlxl** [comment]
That's very nice of you! I just sent you a friend request on Discord
