### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by Snailedlt** [Snailedlt/Markdown-Videos#75]
I need a logo for the project! Do you wanna make it?

The logo should be related to both Markdown and Videos... Other than that I'm open to anything

**Comment by vedranson** [comment]
Hi. I made a logo proposal. According to the Google's image search it's unique.

![md_logo](https://github.com/Snailedlt/Markdown-Videos/assets/32452212/059d1080-6aba-45bb-bfe0-f917b6def80d)

Let me know if you like it.

**Comment by Snailedlt** [comment]
@vedranson wow that was fast! I love it!

Would you be able to make a two comored one also? I want one that fits well with the upcoming website :)

**Comment by Snailedlt** [comment]
Something instead of this:
![](https://user-images.githubusercontent.com/43886029/258410415-c35e8a30-da77-4776-af85-81ff856cf394.png)

**Comment by Snailedlt** [comment]
This is definitely good enough to work on the website btw, so thank you very much! :)

**Comment by vedranson** [comment]
Sure. Here is the logo only, in white-red.

![MDV_logo_white_brackets](https://github.com/Snailedlt/Markdown-Videos/assets/32452212/6b47c10a-9c7f-42c7-b168-fedbd0cf5b17)

From this, you can make versions, add text, etc.. as you like. Not that I wouldn't do it, but i recon you can much quicker adjust the web page appearance to your liking much quicker this way.

**Comment by Snailedlt** [comment]
Thanks a bunch!
I'll be using that for the website then :)

I'm on my phone rn, so not surewhat the filetype is, but I'll need it to be a vector (preferably SVG) for most applications

**Comment by vedranson** [comment]
You're welcome and thank _you_ for writing open source code.
I assumed you'd need a SVG file, so I saved the logo in that format.

![image](https://github.com/Snailedlt/Markdown-Videos/assets/32452212/d2e99865-3a19-487b-8a75-cb090b4b3fc5)

**Comment by Snailedlt** [comment]
Awesome!

Could you upload the code here aswell? I might be able to deploy the site this weekend or the next :)

**Comment by vedranson** [comment]
The SVG file in the previous comment is the code. Just open the file with
your favorite code editor. The screenshot shows the SVG opened in Pycharm.

Jørgen Kalsnes Hagen ***@***.***> schrieb am Sa., 5. Aug.
2023, 12:27:

**Comment by Snailedlt** [comment]
@vedranson I think something's wrong with the svg: 
![image](https://github.com/Snailedlt/Markdown-Videos/assets/43886029/8f6009ba-e204-4eb2-aa29-781ea891978e)

**Comment by Snailedlt** [comment]
nvm, just had to edit out the CDATA tag

Looking good: 
![image](https://github.com/Snailedlt/Markdown-Videos/assets/43886029/324b4366-6c9e-4f52-b912-5ed063f1a0f0)

**Comment by Snailedlt** [comment]
@vedranson The [new website](https://markdown-videos.jorgenkh.no/) is now in production, and uses a [slightly modified version of the logo](https://github.com/Snailedlt/Markdown-Videos/blob/40d568f40d88d36661ee3bc07bbd9f810c6b59dd/apps/web/public/logo.svg).

I hope it looks alright to you. If not feel free to let me know here or via a PR :)

**Comment by Snailedlt** [comment]
Again, thank you very much for the contribution!
